### PR TITLE
mysql bin command for easily opening a mysql shell

### PR DESCRIPTION
**Pull request by rmarscher**

### CODE REVIEW

**Comment by davenuman** [comment]
I tested this and it works for me, but this seems redundant to just doing `drush sqlc`  which works even if the db is empty.

**Comment by rmarscher** [comment]
Ah ok. I'll close this then. I'm a bit new to Drupal dev. Thanks for the feedback.

**Comment by kostajh** [comment]
@davenuman `drush sqlc` doesn't work for me; I get `'unknown': unknown terminal type.`.

``` bash
$ echo $TERM
xterm-256color
```

Other Drush commands work though. Odd.

**Comment by davenuman** [comment]
I'm seeing this same `unknown terminal type` error now too. It was working for me before so I'm looking into a fix.

This situation looks related: https://github.com/weaveworks/scope/pull/969

**Comment by kostajh** [comment]
One thing to note: if you run `entry`, and then type, e.g. `mysql -uroot` you'll also get the error. If you type `echo $TERM` you'll see `unknown`. If you run `export TERM=linux` (again within the container), then you can successfully run `mysql`.

David H Numan writes:

> I'm seeing this same `unknown terminal type` error now too. It was working for me before so I'm looking into a fix.
>
> This situation looks related: https://github.com/weaveworks/scope/pull/969
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/davenuman/bowline/pull/32#issuecomment-190013162


-- 
@kostajh | kosta@kostaharlan.net

**Comment by davenuman** [comment]
Setting the TERM variable in the drush command solved it for me: 42859c0dfb849224e441aa45b3c41f40a3e4e7b5

**Pull request closed without merging**
